vich_uploader:
    db_driver: orm

    mappings:
        article_picture:
            uri_prefix: /assets/images/
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        cycling_shirt_picture:
            uri_prefix: /assets/images/
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
